name: Run tests

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    environment: deployment

    steps:
    - uses: actions/checkout@v3

    - name: Install Binstall
      run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

    - name: Install Shuttle
      run: cargo binstall cargo-shuttle

    - name: Login
      run: cargo shuttle login --api-key $SHUTTLE_API_KEY

    - name: Deploy
      run: cargo shuttle deploy
