name: Run tests

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    environment: deployment

    steps:
    - uses: actions/checkout@v3

    - name: Install Binstall
      run: cargo install cargo-binstall

    - name: Install Shuttle
      run: cargo binstall cargo-shuttle

    - name: Login
      run: cargo shuttle login --api-key $SHUTTLE_API_KEY

    - name: Deploy
      run: cargo shuttle deploy
